name: ✨ Feature request
description: File a feature request
title: "[New Feature]: "
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: 概要
  validations:
    required: true
- type: textarea
  attributes:
    label: 目的
  validations:
    required: true
- type: textarea
  attributes:
    label: 提案内容
  validations:
    required: true
- type: textarea
  attributes:
    label: タスク
    description: 細かいタスクに分解できているなら書き出す
    placeholder: |
      - [ ] XXX
      - [ ] XXX
      - [ ] XXX
  validations:
    required: false
